name: Checks
run-name: Checks, branch:${{ github.ref_name }}, triggered by @${{ github.actor }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches:
      - '**'
  push:
    branches:
      - 'main'
    tags:
      - '**'
  workflow_dispatch: {}

jobs:
  check-permission:
    uses: ./.github/workflows/_permission_check.yaml
    secrets: inherit

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
